apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: filmapi
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: filmapi-stack
data:
  # Configuration nginx runtime (si n√©cessaire)
  NGINX_HOST: "0.0.0.0"
  NGINX_PORT: "8080"
